// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qufzfvwaavvkegfrgmzt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1ZnpmdndhYXZ2a2VnZnJnbXp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI5NzE2NjksImV4cCI6MjA3ODU0NzY2OX0.kfNJ-AEghN9yOE_pOTfl13PS1c1d4n0zulzDYbHAsBo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});